import "./globals.css";
import Navigation from "./ui/Navigation";

export const metadata = {
  title: "Advent 2023",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-screen-md p-4">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
